### ISSUE TITLE
Create converter for Imagio PA device and data

### ISSUE THREAD

**Issue by amasmiller** [amasmiller/PACFISH#1]

**Comment by jgroehl** [comment]
Hi @amasmiller,

Let me know if you have any questions along the way!

I saw your TODO notes in the code and I apologise for being a bit (too) nosy 😋:
- We do not yet support US data. As such, you would probably have to add custom fields for now if you wanted to include these. But if you have suggestions on how to do this, please feel free to open an issue in the PACFISH repo.
- Metadata per frame is generally supported by specifying the respective metadatum as an array (of length len(frames)) e.g. the pulse energy or timestamps would be an array of the given length. In the lom file it seems the metadata is directly attached to each frame via a frame header. This would not be the case in the ipasc format. Here all frames are in the binary data and the metadata is completely separate.

**Comment by amasmiller** [comment]
Hi @jgroehl,

I've added a recommended way to store US data, see what you think.   I understand what you're saying about how other metadatum should be included; and I've implemented as such.

Bryan Clingman will be presenting an overview of our recommended changes at the upcoming meeting in June.

**Comment by jgroehl** [comment]
Looks great! Seems very straightforward to add US data this way.
Looking forward to the recommendations. Will be an excellent starting point for the discussion on version 2 of the format!

**Comment by amasmiller** [comment]
Thanks @jgroehl!

I am wrapping up the pull request.  A few questions about the standard (version "20210916"):

* the units for Detector Orientation are noted as meters, but the text says it is a unit vector.  should it be unitless?

* the example given in Wavelength Range (e.g. "(700, 900, 1.2)") implies the units are nanometers, but the actual units are meters.  either the example should be updated to convert nm -> m, or the field units changed to nm.

* some fields noting "Report if present" in the standard are required for the quality check (was expecting them not to be required?).  for example, if Regions Of Interest is not defined, the text "missing entry "regions_of_interest"" is seen when running the quality check

* the standard references "get_pulse_laser_energy()", but I see "get_pulse_energy()" in the code.  which is correct?

**Comment by amasmiller** [comment]
The use of the scripts developed under this pull request is described in detail in the below picture:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/32115401/173915789-cdc74dcd-690a-4140-8a57-5421a61f5439.png)



This pull request and the above description was reviewed at the IPASC meeting on 2022-06-10, and it was agreed the implementation was sufficient.  Further issues can be created in new tickets.  Closing and merging #2.

**Comment by jgroehl** [comment]
Thanks a lot for the reminder ping @amasmiller!
I'll prioritise looking over the pull request and testing the code with the provided sample data this week!
Already a huge thank you for your participation in our efforts 😊 

Cheers,
Janek
